# -*- coding: utf-8 -*-
"""kiemtra.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LJlwHwtaSVrglOSkUSFyLdiNf-GyKEJB

207CT27556_Nguyễn Trường An

Câu 1
"""

import pandas as pd
data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Eva", "Frank", "Grace", "Hannah", "Ivan", "Jack", "Kelly", "Liam", "Mona", "Nina", "Oscar"],
    "Age": [25, 30, 35, 28, 22, 45, 34, 31, 27, 29, 33, 40, 26, 32, 36],
    "Salary": [50000, 60000, 70000, 55000, 52000, 80000, 72000, 68000, 61000, 59000, 63000, 77000, 53000, 66000, 75000]
}

df = pd.DataFrame(data)
print(df)

"""câu 2"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import scipy.stats as stats
import statsmodels.api as sm
df = pd.read_csv("datakiemtra.csv")
print(df)

"""câu 3

"""

import pandas as pd
file_path = 'datakiemtra.csv'
data = pd.read_csv(file_path)
filtered_data = data[data['Age'] > 28 ]
filtered_data

"""câu 4"""

import pandas as pd
file_path = 'datakiemtra.csv'
data = pd.read_csv(file_path)
salary_mean = data['Salary'].mean()
salary_mean

"""câu 5

"""

import pandas as pd
file_path = 'datakiemtra.csv'
data = pd.read_csv(file_path)
grouped_df = df.groupby('Age')['Salary'].sum().reset_index()
print(grouped_df)

"""câu 6

"""

sorted_df = df.sort_values(by='Salary', ascending=False)

print(sorted_df)

"""câu 7"""

age = df.groupby('Age')['Age'].agg('count')

age.plot.bar()

"""câu 8"""

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

file_path = 'datakiemtra.csv'
df = pd.read_csv('datakiemtra.csv')
data = pd.read_csv(file_path)
plt.figure(figsize=(10, 6))
plt.plot(df.index, df['Salary'], marker='o', linestyle='-', color='b')
plt.title('Salary')
plt.xlabel('Index')
plt.ylabel('Salary')
plt.grid(True)
plt.show()

"""câu 9"""

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

file_path = 'datakiemtra.csv'
df = pd.read_csv('datakiemtra.csv')
data = pd.read_csv(file_path)
age_counts = df['Age'].value_counts()

plt.figure(figsize=(8, 8))
plt.pie(age_counts, labels=age_counts.index, autopct='%1.1f%%', startangle=140)
plt.title('Age Distribution')
plt.show()

"""câu 10"""

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

file_path = 'datakiemtra.csv'
df = pd.read_csv('datakiemtra.csv')
data = pd.read_csv(file_path)

plt.figure(figsize=(10, 6))
plt.scatter(df['Age'], df['Salary'], color='b')
plt.title('Age vs Salary')
plt.xlabel('Age')
plt.ylabel('Salary')
plt.grid(True)
plt.show()

"""câu 11"""

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

file_path = 'datakiemtra.csv'
df = pd.read_csv('datakiemtra.csv')
data = pd.read_csv(file_path)
nan_exists = df.isnull().values.any()

if nan_exists:
    print("Có giá trị NaN trong DataFrame.")
else:
    print("Không có giá trị NaN trong DataFrame.")

"""câu 12"""

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

file_path = 'datakiemtra.csv'
df = pd.read_csv('datakiemtra.csv')
data = pd.read_csv(file_path)
mean_age = df['Age'].mean()

df.loc[df['Age'] > 30, 'Age'] = mean_age

print(df)

"""câu 13"""

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler

file_path = 'datakiemtra.csv'
df = pd.read_csv('datakiemtra.csv')
data = pd.read_csv(file_path)
scaler = MinMaxScaler()
df['Age'] = scaler.fit_transform(df[['Age']])

print(df)

"""câu 14

"""

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler

file_path = 'datakiemtra.csv'
df = pd.read_csv('datakiemtra.csv')
data = pd.read_csv(file_path)
def categorize_age(age):
    if age < 30:
        return 'Young'
    elif 30 <= age <= 60:
        return 'Middle-aged'
    else:
        return 'Old'
df['Age_group'] = df['Age'].apply(categorize_age)

print(df)

"""câu 15

"""

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler

file_path = 'datakiemtra.csv'
df = pd.read_csv('datakiemtra.csv')
data = pd.read_csv(file_path)
df['Salary_pct_change'] = df['Salary'].pct_change()

print(df)

"""câu 16"""

df = df.drop_duplicates(subset=['Name'], keep='first')


print(df)

"""câu 17

Bài kiểm tra số 1
"""