# -*- coding: utf-8 -*-
"""btvn lab1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A0TtTU5SUyRBWww03THsJzLic1EtrzWX
"""

import pandas as pd

# Đọc dữ liệu từ file CSV
file_path = 'dulieuxettuyendaihoc.csv'
df = pd.read_csv(file_path)

# Tính điểm trung bình môn cho từng năm
df['TBM1'] = df[['T1', 'L1', 'H1', 'S1', 'V1', 'X1', 'D1', 'N1']].mean(axis=1)
df['TBM2'] = df[['T2', 'L2', 'H2', 'S2', 'V2', 'X2', 'D2', 'N2']].mean(axis=1)
df['TBM3'] = df[['T3', 'L3', 'H3', 'S3', 'V3', 'X3', 'D3', 'N3']].mean(axis=1)

# Hàm xếp loại
def xep_loai(tbm):
    if tbm < 5.0:
        return 'Y'
    elif 5.0 <= tbm < 6.5:
        return 'TB'
    elif 6.5 <= tbm < 8.0:
        return 'K'
    elif 8.0 <= tbm < 9.0:
        return 'G'
    else:
        return 'XS'

# Tạo các biến xếp loại
df['XL1'] = df['TBM1'].apply(xep_loai)
df['XL2'] = df['TBM2'].apply(xep_loai)
df['XL3'] = df['TBM3'].apply(xep_loai)

df.to_csv(file_path, index=False)

print("Đã tạo và lưu các biến xếp loại thành công!")

import pandas as pd

# Đọc dữ liệu từ file CSV
file_path = 'dulieuxettuyendaihoc.csv'
df = pd.read_csv(file_path)

# Tính điểm trung bình môn cho từng năm
df['TBM1'] = df[['T1', 'L1', 'H1', 'S1', 'V1', 'X1', 'D1', 'N1']].mean(axis=1)
df['TBM2'] = df[['T2', 'L2', 'H2', 'S2', 'V2', 'X2', 'D2', 'N2']].mean(axis=1)
df['TBM3'] = df[['T3', 'L3', 'H3', 'S3', 'V3', 'X3', 'D3', 'N3']].mean(axis=1)

# Hàm chuyển đổi điểm từ thang điểm 10 sang thang điểm 4 bằng phương pháp Min-Max Normalization
def convert_to_us_grade(tbm):
    min_vn, max_vn = 0, 10
    min_us, max_us = 0, 4
    us_grade = ((tbm - min_vn) / (max_vn - min_vn)) * (max_us - min_us) + min_us
    return us_grade

# Tạo các biến US_TBM1, US_TBM2 và US_TBM3
df['US_TBM1'] = df['TBM1'].apply(convert_to_us_grade)
df['US_TBM2'] = df['TBM2'].apply(convert_to_us_grade)
df['US_TBM3'] = df['TBM3'].apply(convert_to_us_grade)

# Lưu kết quả vào file CSV mới
df.to_csv(file_path, index=False)

print("Đã chuyển đổi và lưu các điểm trung bình thành công!")
df.head()

import pandas as pd

file_path = 'dulieuxettuyendaihoc.csv'
df = pd.read_csv(file_path)

def calculate_kqxt(row):
    group = row['KT']
    DH1 = row['T1']
    DH2 = row['L1']
    DH3 = row['H1']

    if group in ['A', 'A1']:
        average_score = (DH1*2 + DH2 + DH3) / 4
    elif group == 'B':
        average_score = (DH1 + DH2*2 + DH3) / 4
    else:
        average_score = (DH1 + DH2 + DH3) / 3

    return 1 if average_score >= 5.0 else 0

df['KQXT'] = df.apply(calculate_kqxt, axis=1)

output_file_path = 'dulieuxettuyendaihoc.csv'
df.to_csv(output_file_path, index=False)

print(df.head())